### PR TITLE
Integrate custom_lint

### PR DESCRIPTION
**Pull request by kuhnroyal**
Now that `custom_lint` supports JSON output, this action can finally be used to run and annotate custom lints 🎉 
The feature is currently disabled by default.
If enabled, it will perform a pretty basic check for the existence of `custom_lint:` in the project before attempting to run.

Closes https://github.com/invertase/github-action-dart-analyzer/issues/199

@rrousselGit cc

### CODE REVIEW

**Comment by kuhnroyal** [comment]
The last Github action ran 9 month ago. I think the failing workflow is due to newer analyzer setting an exit code when encountering an error, or something like that.

**Comment by kuhnroyal** [comment]
Would love a review here 👀

**Comment by rrousselGit** [comment]
I've been told that it's looking good for merge. Thanks for this!

**Comment by kuhnroyal** [comment]
Awesome, hope we can also get a release with this sometime :)

**Pull request merged**
